# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.8"

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    env_file: .env
    networks:
      - inception
    volumes:
      - wp-data:/var/www/html
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - "9000"
    env_file: .env
    networks:
      - inception
    volumes:
      - wp-data:/var/www/html # Path where our wordpress files are present
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - "3306"
    env_file: .env
    networks:
      - inception
    volumes:
      - mysql-data:/var/lib/mysql # Path where MySQL database deploy his persistent files
    restart: always

networks:
  inception:
    driver: bridge

# xavki: DOCKER-COMPOSE - 4. LES VOLUMES PERSISTANTS
# https://www.youtube.com/watch?v=HUXXKYA7j0s
volumes:
  wp-data:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /home/william/data/wordpress

  mysql-data:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /home/william/data/mysql

